# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20170329_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpage',
            name='coctakil',
            field=models.PositiveSmallIntegerField(default='0', help_text='Person number in cocktail mode'),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='sit',
            field=models.PositiveSmallIntegerField(default='0', help_text='Person number in sitted mode'),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='theater',
            field=models.PositiveSmallIntegerField(default='0', help_text='Person number in theater mode'),
        ),
    ]
