# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20170616_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationpage',
            name='cocktail',
            field=models.PositiveSmallIntegerField(default='0', help_text='Person number in cocktail mode', verbose_name='Number cocktail'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='sit',
            field=models.PositiveSmallIntegerField(default='0', help_text='Person number in sitted mode', verbose_name='Number Sit'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='theater',
            field=models.PositiveSmallIntegerField(default='0', help_text='Person number in theater mode', verbose_name='Number theater'),
        ),
    ]
