# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170612_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='promo_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='promo_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='promo_title',
        ),
    ]
